// Generated by CoffeeScript 1.6.3
var Scale;

Scale = (function() {
  function Scale(obj) {
    if (obj == null) {
      obj = {};
    }
    this.size = obj.size || [0, 200];
    this.range = obj.range || [0, 100];
  }

  Scale.prototype.linear = function(num) {
    var full_range, full_size, range_percentage, the;
    the = this;
    full_range = the.range[1] - the.range[0];
    range_percentage = num / the.range[1];
    full_size = the.size[1] - the.size[0];
    return (range_percentage * full_size) + the.size[0];
  };

  return Scale;

})();
